### ISSUE TITLE
On click not all images are shown

### ISSUE THREAD

**Issue by Ktsirakos** [Morioh-Lab/v-lightbox#6]
Hello,

I just faced the following problem.
I have an array with 3 images.
On the preview everything is okay and I have the configuration with 2 cells
![lightbox issue](https://user-images.githubusercontent.com/9413556/96182007-bedc0500-0f2c-11eb-988c-ec1f392d0cda.PNG)

But once I click to see all the images I am getting the result shown below
![Capture](https://user-images.githubusercontent.com/9413556/96182087-de732d80-0f2c-11eb-8f11-64939a6dc1f6.PNG)

Any ideas why this is happening?

I am running:
"@morioh/v-lightbox": "^1.0.3",
"nuxt": "^2.0.0","nuxt": "^2.0.0",

**Comment by nasa8x** [comment]
Can you share error messages on the console?

**Comment by Ktsirakos** [comment]
No issues shown.
Please clone the following repo to reproduce the problem.
https://github.com/Ktsirakos/lightbox-issue-reproduce
Hope this helps.

**Comment by nasa8x** [comment]
Try:
plugins: [
    ["~/plugins/lightbox.js", {ssr: false}]
  ],

**Comment by Ktsirakos** [comment]
`    {
      src: '~/plugins/v-lightbox.js',
      mode: 'client'
    },`

According to this:
https://nuxtjs.org/api/configuration-plugins/

But still doesn't work.

**Comment by nasa8x** [comment]
I tested your project and it still works. Only the theme doesn't look like the demo because you lack the Morioh Theme: https://github.com/Morioh-Lab/morioh

**Comment by Ktsirakos** [comment]
Here is a video of the solution you suggested.
https://www.loom.com/share/202dde4d38da41888a0673c3b077a6d0?from_recorder=1

Can you please commit make a pull request in my project with the soluction that works for you?

**Comment by nasa8x** [comment]
Include demo at: https://github.com/Morioh-Lab/v-lightbox/tree/master/www
